### ISSUE TITLE
[Question] nesting prefixes

### ISSUE THREAD

**Issue by triallax** [sharkdp/purescript-quantities#43]
From the types of "prefix" functions (e.g. `mega`) it seems like I can "nest" prefixes like so: `kilo (mega gram)`. Is this intended, and if not, are there any safeguards against that?

**Comment by sharkdp** [comment]
Thank you for reporting this.

I think you are right. Nesting itself wouldn't be too bad (IMO), but I think the result would be that of the outer prefix instead of a proper composition/multiplication of the prefixes. Example:
- I think it would be okay if `kilo (mega gram) == giga gram`. Similar constructions come up if you have something like `1 kW / g * 1 kg = 1 "kilo kilo" W = 1 MW` 
- I would say that we should fix something if currently `kilo (mega gram) == kilo gram`.
- Completely preventing `kilo (mega gram)` would also be okay for me.

What do you think?

**Comment by triallax** [comment]
I definitely agree that if 2 is the case, it should be fixed. I also think that either 1 or 3 are fine, but I'm leaning towards disallowing it completely since I think it's very unlikely that one would be writing that on purpose and that it's likely to be a mistake (I welcome any invalidating examples). Of course, the expression you provided should still be possible to resolve to `1 MW`, but one could also argue that `1000 kW` is more "correct" in that it keeps the original prefix. That's a discussion for another day though, and if I'm not wrong this issue has no bearing on if it resolves to `1 MW` or `1000 kW`.

**Comment by sharkdp** [comment]
I just checked that `(kilo (mega gram)) == (giga gram)`. I will add a test for that shortly. I think we could then close this ticket?

**Comment by triallax** [comment]
Yes, that sounds good to me.
